# Generated by Django 2.2 on 2020-06-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_users_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
