# Generated by Django 2.2 on 2020-06-09 02:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 9, 2, 45, 59, 600213, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='properties',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 9, 2, 45, 59, 600213, tzinfo=utc)),
        ),
    ]
