# Generated by Django 2.2 on 2020-06-09 18:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20200608_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/agent'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 9, 18, 50, 23, 366621, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='properties',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 9, 18, 50, 23, 366621, tzinfo=utc)),
        ),
    ]
