# Generated by Django 2.2 on 2020-06-10 15:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20200609_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 15, 56, 2, 49155, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='properties',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 15, 56, 2, 49155, tzinfo=utc)),
        ),
    ]
