# Generated by Django 2.2 on 2020-06-10 15:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20200610_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='office_address',
            field=models.CharField(blank=True, default='my', max_length=50),
        ),
        migrations.AlterField(
            model_name='properties',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 15, 56, 38, 141288, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='properties',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 15, 56, 38, 141288, tzinfo=utc)),
        ),
    ]
