# Generated by Django 2.2 on 2020-06-10 17:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_auto_20200610_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='properties',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 17, 25, 1, 871751, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='properties',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 17, 25, 1, 871751, tzinfo=utc)),
        ),
    ]
