# Generated by Django 2.2 on 2020-06-10 17:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_auto_20200610_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_request',
            name='agent_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_request', to='properties.agent'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 17, 49, 2, 368307, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='properties',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 17, 49, 2, 368307, tzinfo=utc)),
        ),
    ]
