# Generated by Django 2.2 on 2020-06-11 19:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20200610_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 11, 19, 3, 37, 678064, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='properties',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 11, 19, 3, 37, 678064, tzinfo=utc)),
        ),
    ]
