# Generated by Django 2.2 on 2020-06-16 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_user_request_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_request',
            name='property_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requested', to='properties.properties'),
        ),
    ]
